services:
  - type: web
    name: alhazmawi-api
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/Categories
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:10000
      - key: JwtSettings__Secret
        value: AlHazmawiDeliverySuperSecretKey2026!#VerySecureKeyWithMinimum32BytesLength
      - key: ConnectionStrings__DefaultConnection
        value: postgresql://alhazmawi_db_user:E6Hk25M9dZ1lXGED1ImWUD9uZRWcbGnB@dpg-daevjevqj5pc73b3kcc0-a/alhazmawi_db
